package dev.adrian.goral.localhivebackend.domain.research;

public enum BenchmarkMeasurementType {
    REQUEST_LATENCY_MS,
    END_TO_END_TIME_MS,
    TIME_TO_FIRST_STATUS_MS,
    TIME_TO_FINAL_STATUS_MS,
    PAYLOAD_REQUEST_BYTES,
    PAYLOAD_RESPONSE_BYTES,
    SERIALIZATION_TIME_MS,
    DESERIALIZATION_TIME_MS,
    ARTIFACT_UPLOAD_TIME_MS,
    ARTIFACT_DOWNLOAD_TIME_MS,
    ROUND_TRIP_COUNT,
    ERROR_COUNT,
    RETRY_COUNT,
    THROUGHPUT_JOBS_PER_MINUTE
}
