package dev.adrian.goral.localhivebackend.domain.research;

public enum ResearchProtocolValidationReasonCode {
    SUPPORTED,
    UNKNOWN_PROTOCOL,
    UNKNOWN_OPERATION,
    UNKNOWN_DATA_TRANSFER_MODE,
    UNKNOWN_PAYLOAD_FORMAT,
    PROTOCOL_PLANNED,
    PROTOCOL_DISABLED,
    OPERATION_NOT_SUPPORTED,
    DATA_TRANSFER_MODE_NOT_SUPPORTED,
    PAYLOAD_FORMAT_NOT_SUPPORTED,
    COMBINATION_NOT_SUPPORTED
}
