package dev.adrian.goral.localhivebackend.domain.research;

public enum ResearchWorkloadValidationReasonCode {
    SUPPORTED,
    UNKNOWN_WORKLOAD,
    PROTOCOL_COMBINATION_NOT_SUPPORTED,
    WORKLOAD_REQUIRES_WORKSPACE_ARTIFACT,
    WORKLOAD_REQUIRES_OUTPUT_ARTIFACTS,
    WORKLOAD_REQUIRES_STREAMING,
    WORKLOAD_REQUIRES_GROUP_OPERATION,
    WORKLOAD_REQUIRES_SINGLE_EXECUTION_OPERATION,
    WORKLOAD_REQUIRES_MERGE_SUPPORT,
    WORKLOAD_EXPECTS_FAILURE,
    WORKLOAD_EXPECTS_CANCEL,
    COMBINATION_NOT_RECOMMENDED
}
