package dev.adrian.goral.localhivebackend.domain.research;

public enum ResearchFaultScenarioValidationReasonCode {
    SUPPORTED,
    UNKNOWN_FAULT_SCENARIO,
    UNKNOWN_WORKLOAD,
    PROTOCOL_COMBINATION_NOT_SUPPORTED,
    WORKLOAD_COMBINATION_NOT_SUPPORTED,
    FAULT_REQUIRES_REST,
    FAULT_REQUIRES_WEBSOCKET,
    FAULT_REQUIRES_SOAP,
    FAULT_REQUIRES_STREAMING,
    FAULT_REQUIRES_GROUP_OPERATION,
    FAULT_REQUIRES_RUNNING_WORKER,
    FAULT_REQUIRES_DOCKER,
    FAULT_REQUIRES_MANUAL_ACTION,
    FAULT_NOT_COMPATIBLE_WITH_OPERATION,
    FAULT_NOT_COMPATIBLE_WITH_WORKLOAD,
    COMBINATION_NOT_RECOMMENDED
}
