spring:
  application:
    name: localhive-panel
    security:
      jwt:
        secret-key: ${JWT_SECRET:6vD7pIQjDYUB3efQun08dLltGwSSomHeTUefBJAjaKS}
        expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/localhive_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:defaultPassword}
    driver-class-name: org.postgresql.Driver

  # Hibernate (ORM)
  jpa:
    # Todo: after thesis defense, change to 'validate' and use Flyway/Liquibase for schema management.
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

localhive:
  features:
    # Main module: Game Server Management (Default: ENABLED)
    game-servers: true

    # Compute module: Distributed Python/C++ tasks (Default: DISABLED)
    compute-grid: true

    # Research module (Master's thesis): Aggregation of latencies, protocols, and CPU usage (DISABLED)
    research-metrics: true

worker:
  heartbeat:
    offline-timeout-seconds: 30
    check-interval-seconds: 10